chore: Update CI actions
styfle/packagephobia pull request #1044
Opened 2024-04-20 05:11 UTC by XhmikosR

2024-04-20 14:52 UTC, styfle commented on .github/workflows/ci.yml
Let's keep the filename the same so we can see the diff here

2024-04-20 15:31 UTC, XhmikosR commented
I kept the patches separate for this reason.

On Sat, Apr 20, 2024, 17:52 Steven ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On .github/workflows/ci.yml
> <https://github.com/styfle/packagephobia/pull/1044#discussion_r1573309147>
> :
>
> Let's keep the filename the same so we can see the diff here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/styfle/packagephobia/pull/1044#pullrequestreview-2013100811>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACVLNOQE33QUC4EH5EJUMDY6J6L3AVCNFSM6AAAAABGQGG6DOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJTGEYDAOBRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-20 15:31 UTC, XhmikosR commented on .github/workflows/ci.yml
I kept the patches selarate for this reason.

2024-04-25 22:36 UTC, styfle commented on .github/workflows/nodejs.yml
> -      - run: corepack enable npm
Please keep corepack so it runs the correct version of npm

2024-04-26 05:40 UTC, XhmikosR commented on .github/workflows/nodejs.yml
> -      - run: corepack enable npm
Done. I also restored npm --version. I wasn't aware of this feature, you learn something new everyday :)

2024-04-26 12:59 UTC, styfle requested changes
Lets change this PR to adding dependabot only.

I don't like the other changes since its not clear the benefit.

2024-04-26 15:20 UTC, XhmikosR commented
Well, there's no permissions specified (which could be even less later), newer actions versions, no more useless matrix and the use of `npm ci` and caching.

https://www.diffchecker.com/4IH8J4Kj/

Feel free to close if you only want the dependabot addition. I personally think the other changes are good.

2024-04-26 17:30 UTC, closed without merging