Add link to GitHub repo
styfle/packagephobia pull request #1056
Opened 2024-08-05 16:11 UTC by fregante

- Will close https://github.com/styfle/packagephobia/issues/1055

It uses [ghub.io](https://ghub.io) to link directly to the repo.

2024-08-06 11:07 UTC, fregante commented on src/components/LinkedLogo.tsx
> +    ),
Pulled from https://github.com/logos and cleaned of extra attributes

2024-08-08 04:13 UTC, styfle requested changes
Thanks for the PR!

I tried visiting “satori” and it fails with 404. 

I’m guessing that you’ll need to pass the version too, not just the name.

2024-08-08 04:52 UTC, fregante commented
It seems to be due to a lack of updates:

- https://github.com/nice-registry/ghub.io/issues/892

Does this component have access to the package.json? If so, it could compute the repo URL directly

2024-08-08 18:44 UTC, fregante commented
Fixed 👍

2024-08-10 19:47 UTC, styfle approved these changes
Perfect, thanks! 🥇

2024-08-10 19:48 UTC, merged