anvaka: add version link too
styfle/packagephobia pull request #858
Opened 2021-11-24 17:10 UTC by XhmikosR

2021-11-24 17:11 UTC, XhmikosR commented on src/components/LinkedLogos.tsx
> +                    : `https://npm.anvaka.com/#/view/2d/${escape(escape(name))}/${version}`
I was wondering, is the double escape needed?

2021-12-01 21:33 UTC, styfle commented on src/components/LinkedLogos.tsx
> +                    : `https://npm.anvaka.com/#/view/2d/${escape(escape(name))}/${version}`
It was added in https://github.com/styfle/packagephobia/pull/126

I checked and it seems like it is necessary since this is not part of the path but its part of the search params, due to `#`

2021-12-01 21:34 UTC, styfle requested changes
The tests need to be updated too

2021-12-02 16:08 UTC, merged

2021-12-02 16:09 UTC, styfle commented
Thanks! 🎉